from abc import ABC, abstractmethod
from typing import AsyncGenerator
import json
import httpx

from bluegill_shared.models import Message

from bluegill_agent.schemas import LLMStreamResponse

class BaseLLMProvider(ABC):
    """
    An abstract class for a LLM provider client. Features methods to interact with the provider API.
    """

    def __init__(self, base_url: str | None) -> None:
        self.base_url = base_url.rstrip("/") if base_url else None
        self._client = httpx.AsyncClient(base_url=base_url or "")

    
    @abstractmethod
    async def generate(
        self, 
        model: str, 
        messages: list[Message], 
        window: int
    ) -> LLMStreamResponse:
        """
        Produces a single response generated by the model where window is the input token window 
        and messages is a list of Message objects representing the conversation context.
        """
        
        raise NotImplementedError


    @abstractmethod
    async def stream(
        self, 
        model: str, 
        messages: list[Message],
        system_prompt: str, 
        window: int,
        think: bool
    ) -> AsyncGenerator[LLMStreamResponse, None]:
        """
        Produces a stream of response objects generated by the model where window is the 
        input token window, messages is a list of Message objects representing the conversation
        context, and system_prompt is a custom prompt that replaces the provider's default
        behavioral system prompt.
        Chunks yielded by the provider API are normalized into LLMStreamResponse objects
        """

        raise NotImplementedError
        yield LLMStreamResponse()
    
    
    @abstractmethod
    async def model_exists(self, model: str) -> bool:
        """
        Calls the provider API to verify the existence of the given model.
        """
        
        raise NotImplementedError
    
    
    def format_messages(self, messages: list[Message]) -> str:
        """
        Formats the given list of Message objects into a model-readable conversation string.
        """
        
        return "\n".join(json.dumps({"role": m.role, "content": m.content}) for m in messages)
