from pydantic import BaseModel
from typing import Literal

from bluegill_agent.schemas.message import Message

class AgentStreamResponse(BaseModel):
    """
    A model that defines async stream chunks yielded by the agent.
    
    Attributes:
        type: The type of message this chunk contains. Possible values are:
            - generate: The response contains standard LLM output.

            - tool_call: The response contains a formatted tool call.

            - tool_result: The response contains the output of tool execution.

            - done: Signifies the end of the stream. 

            - error: Denotes that an agent error occurred. The response contains details about the error.
            
        content: The content of the agent's response.

        tool: The name of the tool used if "type" is either "tool_call" or "tool_result".

        input: The input parameters for the given tool.

        total_duration: Time spent in nanoseconds calling tools and generating responses. Only populated when type == "done".

        token_count: The total number of tokens used by the model. Only populated when type == "done".
        
        context: A tuple containing the full context of the conversation with index 0 containing  messages passed to the agent
                  and index 2 containing messages generated by the agent during the current run_agent() call. 
                  Only populated when type == "done".
    """
    
    type: Literal["generate", "tool_call", "tool_result", "done", "error"]
    content: str | None = None
    tool: str | None = None
    input: dict | None = None
    total_duration: int | None = None
    token_count: int | None = None
    context: tuple[list[Message], list[Message]] | None = None
